// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyvFx3aGlcBdiU1TRqaywCIIwDzBdNxSk',
    appId: '1:518293118753:web:0e65ac93175a613e56e860',
    messagingSenderId: '518293118753',
    projectId: 'task-6851a',
    authDomain: 'task-6851a.firebaseapp.com',
    storageBucket: 'task-6851a.firebasestorage.app',
    measurementId: 'G-GPVRNC7T71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHBApe144b4irnbBceM7lqV-XftiFigc0',
    appId: '1:518293118753:android:4efb3671ca39bd9356e860',
    messagingSenderId: '518293118753',
    projectId: 'task-6851a',
    storageBucket: 'task-6851a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0Akv2hz6_4ZTPr7loSo1q53PXPh5XEE',
    appId: '1:518293118753:ios:8545e0424e7bfa6956e860',
    messagingSenderId: '518293118753',
    projectId: 'task-6851a',
    storageBucket: 'task-6851a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0Akv2hz6_4ZTPr7loSo1q53PXPh5XEE',
    appId: '1:518293118753:ios:8545e0424e7bfa6956e860',
    messagingSenderId: '518293118753',
    projectId: 'task-6851a',
    storageBucket: 'task-6851a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyvFx3aGlcBdiU1TRqaywCIIwDzBdNxSk',
    appId: '1:518293118753:web:36de2e820589033d56e860',
    messagingSenderId: '518293118753',
    projectId: 'task-6851a',
    authDomain: 'task-6851a.firebaseapp.com',
    storageBucket: 'task-6851a.firebasestorage.app',
    measurementId: 'G-0YRP3QRVKZ',
  );
}
